// import { StateSchema, MessagesValue, StateGraph, START, END, ReducedValue } from "@langchain/langgraph";
// import type { GraphNode } from "@langchain/langgraph";
// import { HumanMessage } from "@langchain/core/messages";
// import { mistralModel, cohereModel, geminiModel } from "./model.service.js";
// import { createAgent, providerStrategy } from "langchain";
// import { z } from "zod";

// const State = new StateSchema({
//     messages: MessagesValue,
//     solution_1: new ReducedValue(z.string().default(""), {
//         reducer: (current, next) => {
//             return next
//         }
//     }),
//     solution_2: new ReducedValue(z.string().default(""), {
//         reducer: (current, next) => {
//             return next
//         }
//     }),
//     judge_recommendation: new ReducedValue(
//         z.object({
//             solution_1_score: z.number(),
//             solution_2_score: z.number(),
//         }).default({
//             solution_1_score: 0,
//             solution_2_score: 0,
//         }),
//         {
//             reducer: (current, next) => {
//                 return next;
//             }
//         }
//     ),
// });

// const solutionNode: GraphNode<typeof State> = async (state: typeof State) => {
//     console.log(state)
//     const [mistral_solution, cohere_solution] = await Promise.all([
//         mistralModel.invoke(state.messages[0].text),
//         cohereModel.invoke(state.messages[0].text)
//     ])
//     return {
//         solution_1: mistral_solution.text,
//         solution_2: cohere_solution.text
//     }
// }

// const judgeNode: GraphNode<typeof State> = async (state: typeof State) => {
//     const judgeAgent = createAgent({
//         model: geminiModel,
//         tools: [],
//         responseFormat: providerStrategy(z.object({
//             solution_1_score: z.number().min(0).max(10),
//             solution_2_score: z.number().min(0).max(10),
//         }))
//     })

//     const judgeResponse = await judgeAgent.invoke({

//         messages: [
//             new HumanMessage(
//                 `You are a judge tasked with evaluating two solutions to a problem.

//                 The Problem is : ${state.messages[0].text}.
//                 The fist Solution is: ${state.solution_1}.
//                 The second Solution is: ${state.solution_2}.

//                 Please provide a score between 0 and 10 for each solution, where 0 means the solution is completly incorrect or irrelevant and 10 means the solution is perfect and fully addresses the problem.
//                 `
//             )
//         ]
//     })
//     const result = judgeResponse.structuredResponse

//     return {
//         judge_recommendation: result
//     }
// }

// const graph = new StateGraph(State)
//     .addNode("solution", solutionNode)
//     .addNode("judge", judgeNode)
//     .addEdge(START, "solution")
//     .addEdge("solution", "judge")
//     .addEdge("judge", END)
//     .compile();

// export default async function (userMessage: string) {
//     const result = await graph.invoke({
//         messages: [
//             new HumanMessage(userMessage)
//         ]
//     })
//     console.log(result)
//     return result.messages
// }
import { StateGraph, StateSchema, START, END, type GraphNode, type CompiledStateGraph } from "@langchain/langgraph"
import z from "zod";
import { mistralModel, cohereModel, geminiModel } from "./model.service.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";

const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
})


const solutionNode: GraphNode<typeof state> = async (state) => {

    const [mistralResponse, cohereResponse] = await Promise.all([
        mistralModel.invoke(state.problem),
        cohereModel.invoke(state.problem)
    ])

    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state

    const judge = createAgent({
        model: geminiModel,
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
            solution_1_reasoning: z.string(),
            solution_2_reasoning: z.string(),
        })),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
    })

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evaluate the solutions and provide scores and reasoning.
                `)
        ]
    })


    const {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning
    } = judgeResponse.structuredResponse

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    }

}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile()

export default async function (problem: string) {

    const result = await graph.invoke({
        problem: problem
    })

    return result

}